### ISSUE TITLE
Scripts for checking compliance or cleaning up non-compliant code?

### ISSUE THREAD

**Issue by JeffFessler** [invenia/BlueStyle#48] opened 2020-04-27 16:00 UTC
Anyone know of (Julia?) scripts for checking whether some Julia code complies with BlueStyle?
(Something akin to Coverage.jl but simpler?)

Or better yet, scripts for "pretty printing" (modifying) code to comply?

**Comment by oxinabox** [comment] 2020-04-27 19:55
duplicate of #7

**Closed by oxinabox** 2020-04-27 19:55 UTC
